version: '3.8'

services:
  client:
    build: 
      context: .
      dockerfile: client.Dockerfile
    network_mode: host
    depends_on:
      - server
  server:
    build: 
      context: .
      dockerfile: server.Dockerfile
    network_mode: host

    