/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "get_min_max.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

double_pair *
vetor_min_max_100(vetor *argp, CLIENT *clnt)
{
	static double_pair clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, vetor_min_max,
		(xdrproc_t) xdr_vetor, (caddr_t) argp,
		(xdrproc_t) xdr_double_pair, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
