/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "get_min_max.h"

bool_t
xdr_vetor (XDR *xdrs, vetor *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vetor, MAX_SIZE,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_double_pair (XDR *xdrs, double_pair *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
